export const ActionTypes = {
    FETCH_SHOWS_REQUEST: "FETCH_SHOWS_REQUEST",
    FETCH_SHOWS_SUCCESS: "FETCH_SHOWS_SUCCESS",
    FETCH_SHOWS_FAIL: "FETCH_SHOWS_FAIL",
    FETCH_SHOWS_NAMES_REQUEST: "FETCH_SHOWS_NAMES_REQUEST",
    FETCH_SHOWS_NAMES_SUCCESS: "FETCH_SHOWS_NAMES_SUCCESS",
    FETCH_SHOWS_NAMES_FAIL: "FETCH_SHOWS_NAMES_FAIL",
    FAVORITE_SHOW: "FAVORITE_SHOW"
};